"""modified order schema

Revision ID: d724c6f68024
Revises: e3a532486f2b
Create Date: 2025-01-10 11:00:37.119856

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'd724c6f68024'
down_revision: Union[str, None] = 'e3a532486f2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'order_items',
        sa.Column('subtotal', sa.Float(), nullable=False, server_default='0.0')
    )
    op.alter_column('order_items', 'subtotal', server_default=None)  # Optional: Remove default after migration

    op.alter_column('order_items', 'order_id',
                    existing_type=sa.INTEGER(),
                    nullable=False)
    op.alter_column('order_items', 'product_id',
                    existing_type=sa.INTEGER(),
                    nullable=False)
    op.alter_column('order_items', 'quantity',
                    existing_type=sa.INTEGER(),
                    nullable=False)
    op.alter_column('order_items', 'price_at_time',
                    existing_type=sa.DOUBLE_PRECISION(precision=53),
                    nullable=False)
    op.alter_column('orders', 'total_price',
                    existing_type=sa.DOUBLE_PRECISION(precision=53),
                    nullable=False)
    op.alter_column('orders', 'status',
                    existing_type=sa.VARCHAR(),
                    nullable=False)
# ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'status',
                    existing_type=sa.VARCHAR(),
                    nullable=True)
    op.alter_column('orders', 'total_price',
                    existing_type=sa.DOUBLE_PRECISION(precision=53),
                    nullable=True)
    op.alter_column('order_items', 'price_at_time',
                    existing_type=sa.DOUBLE_PRECISION(precision=53),
                    nullable=True)
    op.alter_column('order_items', 'quantity',
                    existing_type=sa.INTEGER(),
                    nullable=True)
    op.alter_column('order_items', 'product_id',
                    existing_type=sa.INTEGER(),
                    nullable=True)
    op.alter_column('order_items', 'order_id',
                    existing_type=sa.INTEGER(),
                    nullable=True)
    op.drop_column('order_items', 'subtotal')
    # ### end Alembic commands ###
